spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiyin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: MYSQL001007
    #type: com.alibaba.druid.pool.DruidDataSource
